name = "preconnect-web"
compatibility_date = "2026-03-08"
workers_dev = false
main = "./src/worker.js"
routes = [
  { pattern = "web.preconnect.app/*", zone_name = "preconnect.app" }
]

[assets]
directory = "./build/web"
not_found_handling = "single-page-application"
